from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


class UserIntent(BaseModel):
    """
    TITUS Intention Layer.
    Validates the core action the user wants to perform.
    """
    action_type: str = Field(..., description="buy, research, design, control, social")
    parameters: Dict[str, Any] = Field(default_factory=dict)
    priority: int = 1
    human_confirmation_required: bool = True
    voice_preference: bool = Field(True, description="Whether the user wants vocal feedback.")


class PerceptionReport(BaseModel):
    """
    TITUS Sensory Report.
    Unified snapshot of what the system 'feels' currently.
    """
    screen_summary: str = Field(..., description="Description of the active screen context.")
    last_spoken: Optional[str] = None
    ambient_context: Optional[str] = "Office Environment"
    timestamp: float


class TaskStep(BaseModel):
    """
    A single tactical maneuver by an agent.
    """
    agent_id: str
    action: str
    params: Dict[str, Any] = {}


class AutonomousPlan(BaseModel):
    """
    Full strategic orchestration generated by the brain.
    """
    goal: str
    intent: UserIntent
    steps: List[TaskStep]
    estimated_time: str
    reasoning: str


class TelemetryUpdate(BaseModel):
    """
    Real-time status from agents to dashboard.
    """
    agent_id: str
    status: str
    message: str
    timestamp: float
