from shared.base_agent import BaseAgent
from shared.config import Config
from features.action.tools.browser_tool import BrowserTool
from features.action.tools.file_tool import FileTool
import os
import time
import subprocess

class ExecutorAgent(BaseAgent):
    """
    TITUS Digital Sense: The Hands.
    Agent focused on autonomous task execution (Files, Web, etc.)
    """

    def initialize(self):
        print(f"[+] {self.name}: Calibrating motor routines & security protocols...")
        from features.action.bridge.connector import PsiquisBridge
        self.bridge = PsiquisBridge()
        self.status = "ACTIVE"
        self.bridge.sync_agent_status(self.agent_id, self.status, "Execution modules ONLINE")
        time.sleep(0.5)

    def execute(self, task: dict):
        action = task.get("action", "unknown")
        print(f"[*] {self.name}: Initiating autonomous action '{action}'...")
        
        # Report progress
        self.bridge.sync_agent_status(self.agent_id, "EXECUTING", f"Performing {action}")
        
        if action == "CREATE_FILE":
            filename = task.get("filename", "output.txt")
            content = task.get("content", "Generated by TITUS")
            print(f"[*] {self.name}: Writing command to FileTool...")
            res = FileTool.write_file(filename, content)
            
            if res["status"] == "SUCCESS":
                self.bridge.sync_agent_status(self.agent_id, "SUCCESS", f"File {filename} created")
            else:
                self.bridge.sync_agent_status(self.agent_id, "ERROR", res["msg"])
            return res

        elif action == "RUN_SHELL":
            # REAl Laptop Level Automation: Running commands
            command = task.get("command", "")
            print(f"[*] {self.name}: Executing tactical command: {command}")
            try:
                import subprocess
                # Run synchronously for this agent
                result = subprocess.run(command, shell=True, capture_output=True, text=True)
                output = result.stdout if result.returncode == 0 else result.stderr
                self.bridge.sync_agent_status(self.agent_id, "SUCCESS", f"Command executed: {command[:20]}...")
                return {"status": "SUCCESS", "output": output, "code": result.returncode}
            except Exception as e:
                self.bridge.sync_agent_status(self.agent_id, "ERROR", str(e))
                return {"status": "ERROR", "msg": str(e)}

        elif action == "WEB_RESEARCH":
            query = task.get("query", "Latest findings")
            print(f"[*] {self.name}: Dispatching BrowserTool for '{query}'...")
            res = BrowserTool.search(query)
            
            if res["status"] == "SUCCESS":
                status_msg = f"Found {len(res['results'])} intel sources."
                self.bridge.sync_agent_status(self.agent_id, "SUCCESS", status_msg)
            else:
                self.bridge.sync_agent_status(self.agent_id, "ERROR", res["msg"])
            return res

        elif action == "CODE_GEN":
            # Using Claude directly for precision coding
            prompt = task.get("prompt", "")
            print(f"[*] {self.name}: Requesting tactical code from Claude...")
            try:
                from features.cognition.brain import TITUSBrain
                brain = TITUSBrain()
                code = brain.think_with_claude(f"Generate Python code for: {prompt}. Return ONLY the code.")
                self.bridge.sync_agent_status(self.agent_id, "SUCCESS", "Tactical code READY")
                return {"status": "SUCCESS", "code": code}
            except Exception as e:
                return {"status": "ERROR", "msg": str(e)}

        return {"status": "UNKNOWN_ACTION"}

    def shutdown(self):
        print(f"[-] {self.name}: Entering safe state & parking motor routines...")
        self.status = "OFFLINE"
